namespace: codersparks
name: homelab_collection
version: 0.0.6
readme: README.md
authors:
- codersparks

description: A collection of roles for use with my homelab
license:
- MIT
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/codersparks/ansible_homelab_collection
documentation: https://github.com/codersparks/ansible_homelab_collection
homepage: https://github.com/codersparks/ansible_homelab_collection
issues: https://github.com/codersparks/ansible_homelab_collection/issues
