name: 'ansible_homelab_collection CI'
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install ansible dependency
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade ansible

      - name: List contents
        run: 'find ./'

      - name: Get original galaxy file version
        run: 'grep "version:" galaxy.yml'

      - name: Bump version in galaxy.yml
        id: versionbump
        run: echo "::set-output name=version::$(python build_utils/bump_version.py ./galaxy.yml)"

      - name: Get updated galaxy file version
        run: 'grep "version:" galaxy.yml'

      - name: Get saved version
        run: 'echo ${{ steps.versionbump.outputs.version }}'

      - name: Copy files and directories to source
        run: |
          mkdir -p build/src
          mkdir -p build/dist
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: "README.md galaxy.yml"
          directories: "roles"

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force --output-path build/dist

      - name: List build contents
        run: find ./build

      - name: Deploy Collection to ansible galaxy
        run: ansible-galaxy collection publish build/dist/codersparks-homelab_collection-${{ steps.versionbump.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}

      - name: Commit changes etc
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "Performing release for version ${{ steps.versionbump.outputs.version }}"
          git push
          git tag -a "v${{ steps.versionbump.outputs.version }}" -m "Performing release for version ${{ steps.versionbump.outputs.version }}"
          git push --tags
