name: 'ansible_homelab_collection CI'
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: List contents
        run: 'find ./'

      - name: Get original galaxy file version
        run: 'grep "version:" galaxy.yml'

      - name: Bump version in galaxy.yml
        run: python build_utils/bump_version.py ./galaxy.yml

      - name: Get updated galaxy file version
        run: 'grep "version:" galaxy.yml'
